### ISSUE TITLE
Missing curl command

### ISSUE THREAD

**Issue by djcenox** [galal-hussein/rancher-mongo-config#1]
Looks like curl is missing from mongo image.
/opt/rancher/bin/lowest_idx.sh: line 9: curl: command not found
/opt/rancher/bin/lowest_idx.sh: line 24: [: : integer expression expected

**Comment by galal-hussein** [comment]
I used mongo 3.0 image as the main image, this is from inside a mongo:3.0 container:

```
root@d4afb8deeb16:/# curl --version
curl 7.26.0 (x86_64-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

Make sure that you use the docker-compose file described in the README, or it would be easier if you used the compose template from Rancher directly.

**Comment by djcenox** [comment]
Yes, but i got this problem using the official catalog.

**Comment by djcenox** [comment]
Unable to find image 'mongo:3.0' locally
3.0: Pulling from library/mongo
4d690fa98655: Pull complete 
a3ed95caeb02: Pull complete 
250dfb76f241: Pull complete 
21b4523106d1: Pull complete 
7b9be52067e7: Pull complete 
792326f25548: Pull complete 
31799f022138: Pull complete 
0f7a7f5356df: Pull complete 
981d9f006a77: Pull complete 
03913f2c5b05: Pull complete 
Digest: sha256:211e46c14861e23280a661868d0b63716f5968e60a6f66ad0611bc14216aef95
Status: Downloaded newer image for mongo:3.0
/opt/rancher/bin/lowest_idx.sh: line 8: curl: command not found
/opt/rancher/bin/lowest_idx.sh: line 24: [: : integer expression expected

**Comment by galal-hussein** [comment]
Yes it seems that the mongo official image replaced curl with wget in 2.4, and removed it all together in mongo 3.0

https://github.com/docker-library/mongo/commit/4507e9767e0810ebfba7c19438613f37d7843278

Will fix the image, thanks.

**Comment by galal-hussein** [comment]
Pull request added https://github.com/rancher/compose-templates/pull/47 to fix the image.

**Comment by djcenox** [comment]
Thanks

Il venerdì 11 marzo 2016, Hussein Galal notifications@github.com ha
scritto:
