### ISSUE TITLE
Errors on upgrade

### ISSUE THREAD

**Issue by throrin19** [galal-hussein/rancher-mongo-config#2]
Hi, I test to deploy MongoDB from catalog but, after tests, it seems to be an error.

If I upgrade service in the rancher UI (to expose the 27017 port to the host), The replicaset is on error because the config is set with previous MongoDB nodes IPs. 

If I try to unscale to 2 the number of MongoDB nodes, the same problem reappear.

How I can fix this ?

**Comment by galal-hussein** [comment]
It should be solved by adding retain_ip to the rancher-compose so when you upgrade the node instances will have the same ip if they upgraded, they pull request will solve the issue https://github.com/rancher/community-catalog/pull/115

**Comment by throrin19** [comment]
Thanks ;)
